# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: One More Test
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'apis/userprofile/**'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  AZURE_WEBAPP_NAME: openhackp703ii32userprofile    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '12.x'                # set this to the node version to use
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       working-directory: apis/userprofile
    strategy:
      matrix:
        node-version: [12.x]

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

# Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://openhackp703ii32acr.azurecr.io/
          username: ${{ secrets.USERCYZ }}
          password: ${{ secrets.PASSCYZ }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: openhackp703ii32acr.azurecr.io/${{ secrets.USERCYZ }}/openhackp703ii32acr/devopsoh/api-userprofile:${{ github.sha }}
          file: ./Dockerfile
        
      - uses: actions/setup-node@v1

# Runs functional tests
      - name: npm install, build, and test
        run: |
          npm install && npm test
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

# Runs the deploy workflow to Azure

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackp703ii32userprofile'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_86bf552904444e97953aaa7afcd9400e }}
          images: 'openhackp703ii32acr.azurecr.io/${{ secrets.USERCYZ }}/openhackp703ii32acr/devopsoh/api-userprofile:${{ github.sha }}'
