# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Node.js Continuous Integration
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, testing ]
    paths:
      - 'apis/userprofile/**'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       working-directory: apis/userprofile
    strategy:
      matrix:
        node-version: [12.x]

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

# Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Build Info
        run: echo $GITHUB_RUN_NUMBER

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - run: | 
          docker build . -t ${{ secrets.SERVER }}/2/api-userprofile:$GITHUB_RUN_NUMBER
          docker push ${{ secrets.SERVER }}/2/api-userprofile:$GITHUB_RUN_NUMBER

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: openhackp703ii32acr.azurecr.io/${{ secrets.USERNAME }}/devopsoh/api-userprofile:${{ github.sha }}
          file: ./Dockerfile
