# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Node.js Continuous Integration
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, testing ]
    paths:
      - 'apis/userprofile/**'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
       shell: bash
       working-directory: apis/userprofile
    strategy:
      matrix:
        node-version: [12.x]

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

# Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Build Info
        run: echo $GITHUB_RUN_NUMBER

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://openhackp703ii32acr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_8f4145f4ee4e4b929a7506c286d717ce }}
          password: ${{ secrets.AzureAppService_ContainerPassword_d137da87c2f64908bf75c213b610acc3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: openhackp703ii32acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f4145f4ee4e4b929a7506c286d717ce }}/devopsoh/api-userprofile:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhackp703ii32userprofile'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_4e416b480c604379b3b7caf9a86e3ea8 }}
          images: 'openhackp703ii32acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8f4145f4ee4e4b929a7506c286d717ce }}/devopsoh/api-userprofile:${{ github.sha }}'
