# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - openhackp703ii32userprofile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://openhackp703ii32acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_47fe3dc24cc34fa29339456007fa31bf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_117d79083b71400ab7cc23989d7c91a7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: openhackp703ii32acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_47fe3dc24cc34fa29339456007fa31bf }}/devopsoh/api-userprofile:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openhackp703ii32userprofile'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_523fea0cebdd4581ab524563468e997f }}
        images: 'openhackp703ii32acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_47fe3dc24cc34fa29339456007fa31bf }}/devopsoh/api-userprofile:${{ github.sha }}'